Repository fnf-org/TicketBooth, pull requests merged in 2024-08, with the labels that each got.

#259 A slew of performance related changes.
  .envrc
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  Makefile
  Procfile.dev
  app/controllers/application_controller.rb
  app/controllers/events_controller.rb
  app/models/ticket_request.rb
  app/views/events/_event.html.haml
  app/views/events/index.html.haml
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  spec/controllers/payments_controller_spec.rb
  spec/controllers/ticket_requests_controller_spec.rb
  spec/models/ticket_request_spec.rb
Labels: ready-for-re-review, performance

#263 Mfl/fix manual payment
  .rubocop_todo.yml
  .version
  app/controllers/application_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/ticket_requests_controller.rb
  app/helpers/payments_helper.rb
  app/mailers/payment_mailer.rb
  app/models/payment.rb
  app/models/ticket_request.rb
  app/views/payments/new.html.haml
  app/views/ticket_requests/_table_ticket_request_statuses.html.haml
  app/views/ticket_requests/_table_ticket_requests.html.haml
  app/views/ticket_requests/_ticket_request_show.html.haml
  app/views/ticket_requests/show.html.haml
  db/data/20240806020511_payment_status.rb
  db/data_schema.rb
  db/migrate/20240806011401_payment_provider.rb
  db/seeds.rb
  db/structure.sql
  spec/controllers/payments_controller_spec.rb
  spec/controllers/ticket_requests_controller_spec.rb
  spec/factories/payment.rb
  spec/models/payment_spec.rb
Labels: bug-non-blocking, refactor

#279 clean up the logic for ticket requests page
  .version
  app/views/ticket_requests/_table_ticket_requests.html.haml
Labels: bug-non-blocking, refactor

#267 request confirmed mailer
  .version
  app/classes/fnf/events/ticket_request_event.rb
  app/controllers/ticket_requests_controller.rb
  app/mailers/ticket_request_mailer.rb
  app/models/ticket_request.rb
  app/views/ticket_request_mailer/request_approved.html.haml
  app/views/ticket_request_mailer/request_confirmed.html.haml
  app/views/ticket_request_mailer/request_denied.html.haml
  app/views/ticket_request_mailer/request_received.html.haml
  app/views/ticket_requests/_table_ticket_request_statuses.html.haml
  app/views/ticket_requests/_table_ticket_requests.html.haml
  spec/controllers/ticket_requests_controller_spec.rb
  spec/mailers/ticket_request_mailer_spec.rb
Labels: confusing-please-revise, bug-non-blocking, refactor
