Repository fnf-org/TicketBooth, pull requests merged in 2024-05, with the labels that each got.

#107 Modernizing the app helm chart
  deployment/DEPLOYMENT.md
  deployment/chart/Chart.yaml
  deployment/chart/templates/config.yaml
  deployment/chart/templates/deployment.yaml
  deployment/chart/templates/external_secret.yaml
  deployment/chart/templates/hpa.yaml
  deployment/chart/values.yaml
  deployment/env/base.yaml
  deployment/env/production.yaml
Labels: resolve-conflicts, devops-deploy

#125 Downgrading Yarn to 1.22.22
  .yarn-version
  app/controllers/application_controller.rb
  app/views/layouts/application.html.haml
  bin/boot-up
  capistrano/tasks/puma.cap
  config/deploy.rb
  config/deploy/production.rb
  config/newrelic.yml
  package.json
  yarn.lock
Labels: devops-deploy

#127 Hoping to fix asset pipeline; OK in dev.
  Procfile.dev
  app/assets/config/manifest.js
  app/assets/images/logos/nav-bar-logo.png
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/site/global.css.scss
  app/assets/stylesheets/vendor/bootstrap-icons.css
  app/javascript/add_jquery.js
  app/javascript/application.js
  app/javascript/controllers/application.js
  app/javascript/controllers/flash_controller.js
  app/javascript/controllers/flatpickr_controller.js
  app/javascript/controllers/popovers_controller.js
  app/javascript/init_bootstrap.js
  app/javascript/init_flatpickr.js
  app/javascript/init_jquery.js
  app/javascript/init_popup.js
  app/javascript/jquery.js
  app/models/event.rb
  app/models/ticket_request.rb
  app/views/events/_form.html.haml
  app/views/events/edit.html.haml
  app/views/layouts/application.html.haml
  app/views/shared/_nav_main.html.haml
  bin/dev
  config/environments/development.rb
  config/initializers/assets.rb
  package.json
  spec/models/event_spec.rb
  spec/models/ticket_request_spec.rb
  tsconfig.json
  yarn.lock
Labels: ready-for-review

#138 Ability to delete my ticket requests, email confirmations + many other fixes.
  .rubocop_todo.yml
  .version
  Gemfile.lock
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/site/_index.css.scss
  app/assets/stylesheets/site/events.css.scss
  app/assets/stylesheets/site/flash.css.scss
  app/assets/stylesheets/site/fonts.css.scss
  app/assets/stylesheets/site/forms.css.scss
  app/assets/stylesheets/site/global.css.scss
  app/assets/stylesheets/site/nav.css.scss
  app/assets/stylesheets/site/size_overrides.css.scss
  app/controllers/ticket_requests_controller.rb
  app/javascript/controllers/flatpickr_controller.js
  app/models/event.rb
  app/models/ticket_request.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/events/_event_summary.html.haml
  app/views/events/_form.html.haml
  app/views/events/edit.html.haml
  app/views/events/guest_list.html.haml
  app/views/events/index.html.haml
  app/views/events/show.html.haml
  app/views/layouts/application.html.haml
  app/views/payments/_form.html.haml
  app/views/payments/new.html.haml
  app/views/shared/_nav_event.html.haml
  app/views/shared/_nav_event_tabs.html.haml
  app/views/shared/_nav_main.html.haml
  app/views/ticket_requests/_form.html.haml
  app/views/ticket_requests/edit.html.haml
  app/views/ticket_requests/new.html.haml
  app/views/ticket_requests/show.html.haml
  bin/site-index
  config/application.rb
  config/initializers/devise.rb
  config/routes.rb
  package.json
Labels: ready-for-re-review

#159 Fix payment issues
  app/controllers/payments_controller.rb
  app/javascript/controllers/checkout_controller.js
  app/views/payments/_payment.html.haml
  app/views/payments/confirm.html.haml
  config/routes.rb
Labels: bug-blocking

#170 revert stripe key to live
  config/credentials.yml.enc
Labels: work-in-progress

#192 Implements Stripe Refund functionality and wires the button
  app/controllers/ticket_requests_controller.rb
  app/models/payment.rb
  app/models/ticket_request.rb
  app/views/ticket_requests/_table_ticket_requests.html.haml
  app/views/ticket_requests/_ticket_request_show.html.haml
  db/migrate/20240523173316_add_stripe_refund_id_to_payments.rb
  db/structure.sql
  spec/models/payment_spec.rb
Labels: review-requires-updates

#193 Fixing Ticket Request CSV as per request; upgrading gems
  Gemfile.lock
  app/classes/fnf/events/abstract_event.rb
  app/models/ticket_request.rb
  spec/models/ticket_request_spec.rb
Labels: ready-for-review

#194 Making tooltips not part of the form labels
  app/views/ticket_requests/_form.html.haml
Labels: ready-for-review

#195 Adding Download ALL vs Active CSV Button
  app/controllers/ticket_requests_controller.rb
  app/models/ticket_request.rb
  app/views/ticket_requests/_table_ticket_request_statuses.html.haml
Labels: ready-for-review
