Repository fnf-org/TicketBooth, pull requests merged in 2024-04, with the labels that each got.

#92 Making sure all node modules bin/ dirs are in PATH
  .envrc
  Procfile.dev
  bin/print-paths
  bin/shchk
  db/seeds.rb
  development/shell-lib.sh
  development/shell/array.sh
  development/shell/is-loaded.sh
  development/shell/path.sh
  development/shell/utils.sh
  package.json
Labels: ready-for-review

#93 Fixing on-demand CSS assets compliation
  Procfile.dev
  app/assets/stylesheets/global.css.scss
  app/views/events/_form.html.haml
  config/database.yml
  config/environments/development.rb
  package.json
Labels: ready-for-review

#94 Adding default values to Event creation
  app/controllers/events_controller.rb
  app/models/event.rb
Labels: ready-for-review

#95 Developer tooling (vim, psqlrc, etc)
  README.adoc
  bin/install-dev-tooling
  development/config/.psqlrc-macros
  development/config/.vimrc
  development/config/.vimrc.customizations
  docs/make-boot.png
Labels: ready-for-review

#96 Fix user registration + auto-hide error/notice messages from the UI
  Makefile
  Procfile.dev
  README.pdf
  app/assets/stylesheets/global.css.scss
  app/controllers/application_controller.rb
  app/controllers/events_controller.rb
  app/javascript/add_jquery.js
  app/javascript/controllers/flash_controller.js
  app/javascript/controllers/index.js
  app/javascript/popovers.js
  app/models/event.rb
  app/views/devise/registrations/_change_password.html.haml
  app/views/devise/registrations/_form.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/devise/registrations/new.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/application.turbo_stream.erb
  app/views/shared/_flash.html.haml
  app/views/shared/_navigation.html.haml
  bin/boot-up
  config/credentials.yml.enc
  config/environments/development.rb
  config/environments/production.rb
Labels: ready-for-merge

#104 Fixing Dockerfile & upgrade Yarn packages
  .github/workflows/publish.yml
  Dockerfile
  bin/docker-entrypoint
  package-lock.json
  yarn.lock
Labels: devops-deploy

#106 Terraform resources for the application
  .gitignore
  deployment/chart/templates/config.yaml
  deployment/chart/templates/deployment.yaml
  deployment/chart/values.yaml
  deployment/gcp/TODO.md
  deployment/gcp/iam.tf
  deployment/gcp/network.tf
  deployment/gcp/null.tf
  deployment/gcp/secrets.tf
  deployment/gcp/sql.tf
  deployment/gcp/terraform.tf
  deployment/gcp/variables.tf
Labels: devops-deploy
